# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f30b2090e0a1e8af2284edd8906eb5d0252fa285087c2d0ddf8d119fc610ec24c2892d66a29da166696a8e13875b6e3f9f7604b88210946836c45ae598de4af

test:
  secret_key_base: d1b89026d8021557ae6aa7da838a6302ad8fcc37d89401fc1c505b451d554ebec53fd8366a076864ac924fe3d7bfccb9f9ca5e24231bd8caf0abb2ec6ebae004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
