# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da5e2b34a0e0203ab30f6f26c2483a1b29be2e53137dd9f21d856d1090f04df8f2d7cddb8bfb221270e4c5b01ac96ab25e74b20978fa3a12547e5f21e2792ba

test:
  secret_key_base: 50efdfd8056da8d62e8eeeaaf698f29192445db9c3704785aedf8ed6560a7919d955ed7e3099ea50ba77e9f10ff76bb260e5178296f6642185b43354866b2892

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
