# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87590f3e988b302869da0b6e170686f72f245eaabd0da3316a0726f3f9c91a10d134dd29127f7c60f8884e56c787889f6cbc90f2c417ba3f3b47ccf3d8eb74fe

test:
  secret_key_base: 9b809e71ef72f74ff18e1fa02f690cd469512ae6a772302dba5da8878d02f30539d214ffcad5c1923570cbfa1c68d7387d490d5f49c3fec9ebb5facff028f435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
