# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25eea293f2dfa9c2f63f9d04f8c2ceafb1d697f55807665c26be3ec07b956a5ebcc82839a29e3a1a37c60adc37946551ce7b6a7b79be4ea753b2d8bde9a4ccc

test:
  secret_key_base: 299b4e67f289650e4d010792085470f0bc7cad215b4ae46bbdd7ee7e52a2cc280a28ad11fd27c41ff35b163d866feb8ce117a2df22bc312ccd399d8d3f28f233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
