# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab14d0c48bdb0fc79b7e76f29409017f86d8d1d71129153e65edb44d79fead4da9cc14a6a33e2cd20616feb041a510f92ce06a91a655d3f0f5d783dfe50335b1

test:
  secret_key_base: 2c75c5bba151c2921ae4e5743c9338ebeac05e67910cb65458581b5a56ba9f977873de305be16656c3de2317c57250a93601895c3a6cf5b51f15d988b3d08dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
